#pragma once

#include <cstdint>

namespace zb {

// Generated by tools/gen_input.py. Do not edit.
// Host-call indices of these entry points, from the single append-only stub space
// (tools/gen_stubs.py, core/src/gen/hostcalls.inc).
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_copy = 440u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_delete = 441u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_diff = 442u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_fromAssetManager = 443u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getCountry = 444u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getDensity = 445u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getGrammaticalGender = 446u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getKeyboard = 447u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getKeysHidden = 448u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getLanguage = 449u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getLayoutDirection = 450u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getMcc = 451u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getMnc = 452u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getNavHidden = 453u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getNavigation = 454u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getOrientation = 455u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getScreenHeightDp = 456u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getScreenLong = 457u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getScreenRound = 458u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getScreenSize = 459u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getScreenWidthDp = 460u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getSdkVersion = 461u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getSmallestScreenWidthDp = 462u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getTouchscreen = 463u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getUiModeNight = 464u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_getUiModeType = 465u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_isBetterThan = 466u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_match = 467u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_new = 468u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setCountry = 469u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setDensity = 470u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setGrammaticalGender = 471u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setKeyboard = 472u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setKeysHidden = 473u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setLanguage = 474u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setLayoutDirection = 475u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setMcc = 476u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setMnc = 477u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setNavHidden = 478u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setNavigation = 479u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setOrientation = 480u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setScreenHeightDp = 481u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setScreenLong = 482u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setScreenRound = 483u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setScreenSize = 484u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setScreenWidthDp = 485u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setSdkVersion = 486u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setSmallestScreenWidthDp = 487u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setTouchscreen = 488u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setUiModeNight = 489u;
inline constexpr std::uint32_t ZB_CONFIG_HC_AConfiguration_setUiModeType = 490u;

inline constexpr std::uint32_t ZB_CONFIG_HC_FIRST = 440u;
inline constexpr std::uint32_t ZB_CONFIG_HC_LAST = 490u;

}  // namespace zb
