#pragma once

#include <cstddef>
#include <cstdint>

namespace zb {

// Generated by tools/gen_ndk.py. Do not edit.
//
// The device configuration, abstract so the host tests can supply their own. A
// configuration is a host object; the guest holds a 32-bit handle for it.
class ConfigurationBackend {
public:
    virtual ~ConfigurationBackend() = default;

    // Hand-written entry points: the object's life, the asset manager and the two
    // two-character fields, which cross as guest memory rather than as values.
    virtual void* create() = 0;
    virtual void destroy(void* config) = 0;
    virtual void from_asset_manager(void* config, void* asset_manager) = 0;
    // Writes exactly two characters, unpadded, as the NDK does.
    virtual void get_language(void* config, char* out) = 0;
    virtual void get_country(void* config, char* out) = 0;
    virtual void set_language(void* config, const char* language) = 0;
    virtual void set_country(void* config, const char* country) = 0;

    // Generated accessors.
    virtual void AConfiguration_copy(void* /* dest */, void* /* src */) { }
    virtual std::int32_t AConfiguration_diff(void* /* config1 */, void* /* config2 */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getDensity(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getGrammaticalGender(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getKeyboard(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getKeysHidden(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getLayoutDirection(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getMcc(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getMnc(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getNavHidden(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getNavigation(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getOrientation(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getScreenHeightDp(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getScreenLong(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getScreenRound(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getScreenSize(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getScreenWidthDp(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getSdkVersion(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getSmallestScreenWidthDp(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getTouchscreen(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getUiModeNight(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_getUiModeType(void* /* config */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_isBetterThan(void* /* base */, void* /* test */, void* /* requested */) { return std::int32_t{}; }
    virtual std::int32_t AConfiguration_match(void* /* base */, void* /* requested */) { return std::int32_t{}; }
    virtual void AConfiguration_setDensity(void* /* config */, std::int32_t /* density */) { }
    virtual void AConfiguration_setGrammaticalGender(void* /* config */, std::int32_t /* value */) { }
    virtual void AConfiguration_setKeyboard(void* /* config */, std::int32_t /* keyboard */) { }
    virtual void AConfiguration_setKeysHidden(void* /* config */, std::int32_t /* keysHidden */) { }
    virtual void AConfiguration_setLayoutDirection(void* /* config */, std::int32_t /* value */) { }
    virtual void AConfiguration_setMcc(void* /* config */, std::int32_t /* mcc */) { }
    virtual void AConfiguration_setMnc(void* /* config */, std::int32_t /* mnc */) { }
    virtual void AConfiguration_setNavHidden(void* /* config */, std::int32_t /* navHidden */) { }
    virtual void AConfiguration_setNavigation(void* /* config */, std::int32_t /* navigation */) { }
    virtual void AConfiguration_setOrientation(void* /* config */, std::int32_t /* orientation */) { }
    virtual void AConfiguration_setScreenHeightDp(void* /* config */, std::int32_t /* value */) { }
    virtual void AConfiguration_setScreenLong(void* /* config */, std::int32_t /* screenLong */) { }
    virtual void AConfiguration_setScreenRound(void* /* config */, std::int32_t /* screenRound */) { }
    virtual void AConfiguration_setScreenSize(void* /* config */, std::int32_t /* screenSize */) { }
    virtual void AConfiguration_setScreenWidthDp(void* /* config */, std::int32_t /* value */) { }
    virtual void AConfiguration_setSdkVersion(void* /* config */, std::int32_t /* sdkVersion */) { }
    virtual void AConfiguration_setSmallestScreenWidthDp(void* /* config */, std::int32_t /* value */) { }
    virtual void AConfiguration_setTouchscreen(void* /* config */, std::int32_t /* touchscreen */) { }
    virtual void AConfiguration_setUiModeNight(void* /* config */, std::int32_t /* uiModeNight */) { }
    virtual void AConfiguration_setUiModeType(void* /* config */, std::int32_t /* uiModeType */) { }
};

}  // namespace zb
