// Generated by tools/gen_egl.py. Do not edit.
#pragma once

#include <bit>
#include <cstdint>
#include <initializer_list>
#include <type_traits>

namespace zb {

using EGLint = std::int32_t;
using EGLenum = std::uint32_t;
using EGLBoolean = std::uint32_t;
using EGLAttrib = std::intptr_t;
using EGLTime = std::uint64_t;
using EGLDisplay = void*;
using EGLConfig = void*;
using EGLContext = void*;
using EGLSurface = void*;
using EGLClientBuffer = void*;
using EGLImage = void*;
using EGLSync = void*;
using EGLNativeWindowType = void*;
using EGLNativeDisplayType = void*;
using EGLNativePixmapType = void*;
using __eglMustCastToProperFunctionPointerType = void*;

inline constexpr EGLint kEglSuccess = 0x3000;
inline constexpr EGLint kEglBadDisplay = 0x3008;
inline constexpr EGLint kEglBadContext = 0x3006;
inline constexpr EGLint kEglBadSurface = 0x300d;
inline constexpr EGLint kEglBadParameter = 0x3004;

template <typename T>
inline std::uint64_t egl_backend_word(T value) {
    if constexpr (std::is_pointer_v<T>) {
        return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(value));
    } else if constexpr (std::is_signed_v<T>) {
        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<T>>(value));
    } else {
        return static_cast<std::uint64_t>(value);
    }
}

// The portable EGL seam. Android overrides the typed entry points; host tests use
// invoke() to record the same typed calls without linking a real EGL driver.
class EglBackend {
public:
    virtual ~EglBackend() = default;

    virtual EGLBoolean eglBindAPI(EGLenum api) {
        return static_cast<EGLBoolean>(invoke("eglBindAPI", {egl_backend_word(api)}));
    }
    virtual EGLBoolean eglBindTexImage(EGLDisplay dpy, EGLSurface surface, EGLint buffer) {
        return static_cast<EGLBoolean>(invoke("eglBindTexImage", {egl_backend_word(dpy), egl_backend_word(surface), egl_backend_word(buffer)}));
    }
    virtual EGLBoolean eglChooseConfig(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config) {
        return static_cast<EGLBoolean>(invoke("eglChooseConfig", {egl_backend_word(dpy), egl_backend_word(attrib_list), egl_backend_word(configs), egl_backend_word(config_size), egl_backend_word(num_config)}));
    }
    virtual EGLint eglClientWaitSync(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout) {
        return static_cast<EGLint>(invoke("eglClientWaitSync", {egl_backend_word(dpy), egl_backend_word(sync), egl_backend_word(flags), egl_backend_word(timeout)}));
    }
    virtual EGLBoolean eglCopyBuffers(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target) {
        return static_cast<EGLBoolean>(invoke("eglCopyBuffers", {egl_backend_word(dpy), egl_backend_word(surface), egl_backend_word(target)}));
    }
    virtual EGLContext eglCreateContext(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list) {
        return reinterpret_cast<EGLContext>(static_cast<std::uintptr_t>(invoke("eglCreateContext", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(share_context), egl_backend_word(attrib_list)})));
    }
    virtual EGLImage eglCreateImage(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib *attrib_list) {
        return reinterpret_cast<EGLImage>(static_cast<std::uintptr_t>(invoke("eglCreateImage", {egl_backend_word(dpy), egl_backend_word(ctx), egl_backend_word(target), egl_backend_word(buffer), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreatePbufferFromClientBuffer(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreatePbufferFromClientBuffer", {egl_backend_word(dpy), egl_backend_word(buftype), egl_backend_word(buffer), egl_backend_word(config), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreatePbufferSurface(EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreatePbufferSurface", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreatePixmapSurface(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreatePixmapSurface", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(pixmap), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreatePlatformPixmapSurface(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLAttrib *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreatePlatformPixmapSurface", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(native_pixmap), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreatePlatformWindowSurface(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreatePlatformWindowSurface", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(native_window), egl_backend_word(attrib_list)})));
    }
    virtual EGLSync eglCreateSync(EGLDisplay dpy, EGLenum type, const EGLAttrib *attrib_list) {
        return reinterpret_cast<EGLSync>(static_cast<std::uintptr_t>(invoke("eglCreateSync", {egl_backend_word(dpy), egl_backend_word(type), egl_backend_word(attrib_list)})));
    }
    virtual EGLSurface eglCreateWindowSurface(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglCreateWindowSurface", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(win), egl_backend_word(attrib_list)})));
    }
    virtual EGLBoolean eglDestroyContext(EGLDisplay dpy, EGLContext ctx) {
        return static_cast<EGLBoolean>(invoke("eglDestroyContext", {egl_backend_word(dpy), egl_backend_word(ctx)}));
    }
    virtual EGLBoolean eglDestroyImage(EGLDisplay dpy, EGLImage image) {
        return static_cast<EGLBoolean>(invoke("eglDestroyImage", {egl_backend_word(dpy), egl_backend_word(image)}));
    }
    virtual EGLBoolean eglDestroySurface(EGLDisplay dpy, EGLSurface surface) {
        return static_cast<EGLBoolean>(invoke("eglDestroySurface", {egl_backend_word(dpy), egl_backend_word(surface)}));
    }
    virtual EGLBoolean eglDestroySync(EGLDisplay dpy, EGLSync sync) {
        return static_cast<EGLBoolean>(invoke("eglDestroySync", {egl_backend_word(dpy), egl_backend_word(sync)}));
    }
    virtual EGLBoolean eglGetConfigAttrib(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value) {
        return static_cast<EGLBoolean>(invoke("eglGetConfigAttrib", {egl_backend_word(dpy), egl_backend_word(config), egl_backend_word(attribute), egl_backend_word(value)}));
    }
    virtual EGLBoolean eglGetConfigs(EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config) {
        return static_cast<EGLBoolean>(invoke("eglGetConfigs", {egl_backend_word(dpy), egl_backend_word(configs), egl_backend_word(config_size), egl_backend_word(num_config)}));
    }
    virtual EGLContext eglGetCurrentContext(void) {
        return reinterpret_cast<EGLContext>(static_cast<std::uintptr_t>(invoke("eglGetCurrentContext", {})));
    }
    virtual EGLDisplay eglGetCurrentDisplay(void) {
        return reinterpret_cast<EGLDisplay>(static_cast<std::uintptr_t>(invoke("eglGetCurrentDisplay", {})));
    }
    virtual EGLSurface eglGetCurrentSurface(EGLint readdraw) {
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(invoke("eglGetCurrentSurface", {egl_backend_word(readdraw)})));
    }
    virtual EGLDisplay eglGetDisplay(EGLNativeDisplayType display_id) {
        return reinterpret_cast<EGLDisplay>(static_cast<std::uintptr_t>(invoke("eglGetDisplay", {egl_backend_word(display_id)})));
    }
    virtual EGLint eglGetError(void) {
        return static_cast<EGLint>(invoke("eglGetError", {}));
    }
    virtual EGLDisplay eglGetPlatformDisplay(EGLenum platform, void *native_display, const EGLAttrib *attrib_list) {
        return reinterpret_cast<EGLDisplay>(static_cast<std::uintptr_t>(invoke("eglGetPlatformDisplay", {egl_backend_word(platform), egl_backend_word(native_display), egl_backend_word(attrib_list)})));
    }
    virtual __eglMustCastToProperFunctionPointerType eglGetProcAddress(const char *procname) {
        return reinterpret_cast<__eglMustCastToProperFunctionPointerType>(static_cast<std::uintptr_t>(invoke("eglGetProcAddress", {egl_backend_word(procname)})));
    }
    virtual EGLBoolean eglGetSyncAttrib(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib *value) {
        return static_cast<EGLBoolean>(invoke("eglGetSyncAttrib", {egl_backend_word(dpy), egl_backend_word(sync), egl_backend_word(attribute), egl_backend_word(value)}));
    }
    virtual EGLBoolean eglInitialize(EGLDisplay dpy, EGLint *major, EGLint *minor) {
        return static_cast<EGLBoolean>(invoke("eglInitialize", {egl_backend_word(dpy), egl_backend_word(major), egl_backend_word(minor)}));
    }
    virtual EGLBoolean eglMakeCurrent(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx) {
        return static_cast<EGLBoolean>(invoke("eglMakeCurrent", {egl_backend_word(dpy), egl_backend_word(draw), egl_backend_word(read), egl_backend_word(ctx)}));
    }
    virtual EGLenum eglQueryAPI(void) {
        return static_cast<EGLenum>(invoke("eglQueryAPI", {}));
    }
    virtual EGLBoolean eglQueryContext(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value) {
        return static_cast<EGLBoolean>(invoke("eglQueryContext", {egl_backend_word(dpy), egl_backend_word(ctx), egl_backend_word(attribute), egl_backend_word(value)}));
    }
    virtual const char * eglQueryString(EGLDisplay dpy, EGLint name) {
        return reinterpret_cast<const char *>(static_cast<std::uintptr_t>(invoke("eglQueryString", {egl_backend_word(dpy), egl_backend_word(name)})));
    }
    virtual EGLBoolean eglQuerySurface(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value) {
        return static_cast<EGLBoolean>(invoke("eglQuerySurface", {egl_backend_word(dpy), egl_backend_word(surface), egl_backend_word(attribute), egl_backend_word(value)}));
    }
    virtual EGLBoolean eglReleaseTexImage(EGLDisplay dpy, EGLSurface surface, EGLint buffer) {
        return static_cast<EGLBoolean>(invoke("eglReleaseTexImage", {egl_backend_word(dpy), egl_backend_word(surface), egl_backend_word(buffer)}));
    }
    virtual EGLBoolean eglReleaseThread(void) {
        return static_cast<EGLBoolean>(invoke("eglReleaseThread", {}));
    }
    virtual EGLBoolean eglSurfaceAttrib(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value) {
        return static_cast<EGLBoolean>(invoke("eglSurfaceAttrib", {egl_backend_word(dpy), egl_backend_word(surface), egl_backend_word(attribute), egl_backend_word(value)}));
    }
    virtual EGLBoolean eglSwapBuffers(EGLDisplay dpy, EGLSurface surface) {
        return static_cast<EGLBoolean>(invoke("eglSwapBuffers", {egl_backend_word(dpy), egl_backend_word(surface)}));
    }
    virtual EGLBoolean eglSwapInterval(EGLDisplay dpy, EGLint interval) {
        return static_cast<EGLBoolean>(invoke("eglSwapInterval", {egl_backend_word(dpy), egl_backend_word(interval)}));
    }
    virtual EGLBoolean eglTerminate(EGLDisplay dpy) {
        return static_cast<EGLBoolean>(invoke("eglTerminate", {egl_backend_word(dpy)}));
    }
    virtual EGLBoolean eglWaitClient(void) {
        return static_cast<EGLBoolean>(invoke("eglWaitClient", {}));
    }
    virtual EGLBoolean eglWaitGL(void) {
        return static_cast<EGLBoolean>(invoke("eglWaitGL", {}));
    }
    virtual EGLBoolean eglWaitNative(EGLint engine) {
        return static_cast<EGLBoolean>(invoke("eglWaitNative", {egl_backend_word(engine)}));
    }
    virtual EGLBoolean eglWaitSync(EGLDisplay dpy, EGLSync sync, EGLint flags) {
        return static_cast<EGLBoolean>(invoke("eglWaitSync", {egl_backend_word(dpy), egl_backend_word(sync), egl_backend_word(flags)}));
    }

protected:
    virtual std::uint64_t invoke(const char* name,
                                 std::initializer_list<std::uint64_t> arguments) = 0;
};

}  // namespace zb
