// Generated by tools/gen_egl.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace zb {

inline constexpr std::uint32_t kEglHostCallFirst = 168u;
inline constexpr std::uint32_t kEglHostCallLast = 211u;
inline constexpr std::size_t kEglHostCallCount = 44u;

inline constexpr std::uint32_t ZB_EGL_HC_eglBindAPI = 168u;
inline constexpr std::uint32_t ZB_EGL_HC_eglBindTexImage = 169u;
inline constexpr std::uint32_t ZB_EGL_HC_eglChooseConfig = 170u;
inline constexpr std::uint32_t ZB_EGL_HC_eglClientWaitSync = 171u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCopyBuffers = 172u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreateContext = 173u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreateImage = 174u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreatePbufferFromClientBuffer = 175u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreatePbufferSurface = 176u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreatePixmapSurface = 177u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreatePlatformPixmapSurface = 178u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreatePlatformWindowSurface = 179u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreateSync = 180u;
inline constexpr std::uint32_t ZB_EGL_HC_eglCreateWindowSurface = 181u;
inline constexpr std::uint32_t ZB_EGL_HC_eglDestroyContext = 182u;
inline constexpr std::uint32_t ZB_EGL_HC_eglDestroyImage = 183u;
inline constexpr std::uint32_t ZB_EGL_HC_eglDestroySurface = 184u;
inline constexpr std::uint32_t ZB_EGL_HC_eglDestroySync = 185u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetConfigAttrib = 186u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetConfigs = 187u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetCurrentContext = 188u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetCurrentDisplay = 189u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetCurrentSurface = 190u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetDisplay = 191u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetError = 192u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetPlatformDisplay = 193u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetProcAddress = 194u;
inline constexpr std::uint32_t ZB_EGL_HC_eglGetSyncAttrib = 195u;
inline constexpr std::uint32_t ZB_EGL_HC_eglInitialize = 196u;
inline constexpr std::uint32_t ZB_EGL_HC_eglMakeCurrent = 197u;
inline constexpr std::uint32_t ZB_EGL_HC_eglQueryAPI = 198u;
inline constexpr std::uint32_t ZB_EGL_HC_eglQueryContext = 199u;
inline constexpr std::uint32_t ZB_EGL_HC_eglQueryString = 200u;
inline constexpr std::uint32_t ZB_EGL_HC_eglQuerySurface = 201u;
inline constexpr std::uint32_t ZB_EGL_HC_eglReleaseTexImage = 202u;
inline constexpr std::uint32_t ZB_EGL_HC_eglReleaseThread = 203u;
inline constexpr std::uint32_t ZB_EGL_HC_eglSurfaceAttrib = 204u;
inline constexpr std::uint32_t ZB_EGL_HC_eglSwapBuffers = 205u;
inline constexpr std::uint32_t ZB_EGL_HC_eglSwapInterval = 206u;
inline constexpr std::uint32_t ZB_EGL_HC_eglTerminate = 207u;
inline constexpr std::uint32_t ZB_EGL_HC_eglWaitClient = 208u;
inline constexpr std::uint32_t ZB_EGL_HC_eglWaitGL = 209u;
inline constexpr std::uint32_t ZB_EGL_HC_eglWaitNative = 210u;
inline constexpr std::uint32_t ZB_EGL_HC_eglWaitSync = 211u;

struct EglHostCallInfo {
    std::uint32_t index;
    const char* name;
};

inline constexpr std::array<EglHostCallInfo, kEglHostCallCount> kEglHostCalls{{
    {168u, "eglBindAPI"},
    {169u, "eglBindTexImage"},
    {170u, "eglChooseConfig"},
    {171u, "eglClientWaitSync"},
    {172u, "eglCopyBuffers"},
    {173u, "eglCreateContext"},
    {174u, "eglCreateImage"},
    {175u, "eglCreatePbufferFromClientBuffer"},
    {176u, "eglCreatePbufferSurface"},
    {177u, "eglCreatePixmapSurface"},
    {178u, "eglCreatePlatformPixmapSurface"},
    {179u, "eglCreatePlatformWindowSurface"},
    {180u, "eglCreateSync"},
    {181u, "eglCreateWindowSurface"},
    {182u, "eglDestroyContext"},
    {183u, "eglDestroyImage"},
    {184u, "eglDestroySurface"},
    {185u, "eglDestroySync"},
    {186u, "eglGetConfigAttrib"},
    {187u, "eglGetConfigs"},
    {188u, "eglGetCurrentContext"},
    {189u, "eglGetCurrentDisplay"},
    {190u, "eglGetCurrentSurface"},
    {191u, "eglGetDisplay"},
    {192u, "eglGetError"},
    {193u, "eglGetPlatformDisplay"},
    {194u, "eglGetProcAddress"},
    {195u, "eglGetSyncAttrib"},
    {196u, "eglInitialize"},
    {197u, "eglMakeCurrent"},
    {198u, "eglQueryAPI"},
    {199u, "eglQueryContext"},
    {200u, "eglQueryString"},
    {201u, "eglQuerySurface"},
    {202u, "eglReleaseTexImage"},
    {203u, "eglReleaseThread"},
    {204u, "eglSurfaceAttrib"},
    {205u, "eglSwapBuffers"},
    {206u, "eglSwapInterval"},
    {207u, "eglTerminate"},
    {208u, "eglWaitClient"},
    {209u, "eglWaitGL"},
    {210u, "eglWaitNative"},
    {211u, "eglWaitSync"},
}};

}  // namespace zb
