#pragma once

#include <cstddef>
#include <cstdint>

namespace zb {

// Generated by tools/gen_ndk.py. Do not edit.
//
// The input side of the platform, abstract so the host tests can supply their own. Events
// and queues are host objects; this interface speaks in host pointers, and turning those
// into the 32-bit handles the guest sees is HostInput's job.
class InputBackend {
public:
    virtual ~InputBackend() = default;

    // Hand-written entry points: the queue lifecycle and the event handle's life.
    virtual std::int32_t queue_has_events(void* queue) = 0;
    // Returns the next event, or nullptr when there is none; status is the NDK's result.
    virtual void* queue_get_event(void* queue, std::int32_t& status) = 0;
    virtual std::int32_t queue_pre_dispatch(void* queue, void* event) = 0;
    virtual void queue_finish_event(void* queue, void* event, std::int32_t handled) = 0;
    // Attaches the queue to the real looper of the calling host thread, or detaches it.
    // The looper is the thread's own: a host AInputQueue has no descriptor we could poll
    // ourselves, so the queue is given to a real Android looper on that same thread.
    // `data` is the guest's own value, round-tripped: the looper hands it back from
    // poll, and the guest reads its own word again. No host pointer is involved.
    // `looper` is the real looper the queue belongs to, as HostLooper resolved it; 0
    // means the calling thread's own. A queue attached to the wrong looper is never
    // polled, and the framework waits out its five seconds for an event nobody took.
    virtual void queue_attach_looper(void* queue, std::int32_t ident, void* data,
                                     std::uint64_t looper) = 0;
    virtual void queue_detach_looper(void* queue) = 0;

    // Generated accessors.
    virtual std::int32_t AInputEvent_getDeviceId(const void* /* event */) { return std::int32_t{}; }
    virtual std::int32_t AInputEvent_getSource(const void* /* event */) { return std::int32_t{}; }
    virtual std::int32_t AInputEvent_getType(const void* /* event */) { return std::int32_t{}; }
    virtual std::int32_t AKeyEvent_getAction(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int64_t AKeyEvent_getDownTime(const void* /* key_event */) { return std::int64_t{}; }
    virtual std::int64_t AKeyEvent_getEventTime(const void* /* key_event */) { return std::int64_t{}; }
    virtual std::int32_t AKeyEvent_getFlags(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int32_t AKeyEvent_getKeyCode(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int32_t AKeyEvent_getMetaState(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int32_t AKeyEvent_getRepeatCount(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int32_t AKeyEvent_getScanCode(const void* /* key_event */) { return std::int32_t{}; }
    virtual std::int32_t AMotionEvent_getAction(const void* /* motion_event */) { return std::int32_t{}; }
    virtual std::int32_t AMotionEvent_getActionButton(const void* /* motion_event */) { return std::int32_t{}; }
    virtual float AMotionEvent_getAxisValue(const void* /* motion_event */, std::int32_t /* axis */, std::size_t /* pointer_index */) { return float{}; }
    virtual std::int32_t AMotionEvent_getButtonState(const void* /* motion_event */) { return std::int32_t{}; }
    virtual std::int32_t AMotionEvent_getClassification(const void* /* motion_event */) { return std::int32_t{}; }
    virtual std::int64_t AMotionEvent_getDownTime(const void* /* motion_event */) { return std::int64_t{}; }
    virtual std::int32_t AMotionEvent_getEdgeFlags(const void* /* motion_event */) { return std::int32_t{}; }
    virtual std::int64_t AMotionEvent_getEventTime(const void* /* motion_event */) { return std::int64_t{}; }
    virtual std::int32_t AMotionEvent_getFlags(const void* /* motion_event */) { return std::int32_t{}; }
    virtual float AMotionEvent_getHistoricalAxisValue(const void* /* motion_event */, std::int32_t /* axis */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual std::int64_t AMotionEvent_getHistoricalEventTime(const void* /* motion_event */, std::size_t /* history_index */) { return std::int64_t{}; }
    virtual float AMotionEvent_getHistoricalOrientation(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalPressure(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalRawX(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalRawY(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalSize(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalToolMajor(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalToolMinor(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalTouchMajor(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalTouchMinor(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalX(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual float AMotionEvent_getHistoricalY(const void* /* motion_event */, std::size_t /* pointer_index */, std::size_t /* history_index */) { return float{}; }
    virtual std::size_t AMotionEvent_getHistorySize(const void* /* motion_event */) { return std::size_t{}; }
    virtual std::int32_t AMotionEvent_getMetaState(const void* /* motion_event */) { return std::int32_t{}; }
    virtual float AMotionEvent_getOrientation(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual std::size_t AMotionEvent_getPointerCount(const void* /* motion_event */) { return std::size_t{}; }
    virtual std::int32_t AMotionEvent_getPointerId(const void* /* motion_event */, std::size_t /* pointer_index */) { return std::int32_t{}; }
    virtual float AMotionEvent_getPressure(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getRawX(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getRawY(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getSize(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getToolMajor(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getToolMinor(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual std::int32_t AMotionEvent_getToolType(const void* /* motion_event */, std::size_t /* pointer_index */) { return std::int32_t{}; }
    virtual float AMotionEvent_getTouchMajor(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getTouchMinor(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getX(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getXOffset(const void* /* motion_event */) { return float{}; }
    virtual float AMotionEvent_getXPrecision(const void* /* motion_event */) { return float{}; }
    virtual float AMotionEvent_getY(const void* /* motion_event */, std::size_t /* pointer_index */) { return float{}; }
    virtual float AMotionEvent_getYOffset(const void* /* motion_event */) { return float{}; }
    virtual float AMotionEvent_getYPrecision(const void* /* motion_event */) { return float{}; }
};

}  // namespace zb
