#pragma once

#include <cstdint>

namespace zb {

// Generated by tools/gen_input.py. Do not edit.
// Host-call indices of these entry points, from the single append-only stub space
// (tools/gen_stubs.py, core/src/gen/hostcalls.inc).
inline constexpr std::uint32_t ZB_INPUT_HC_AInputEvent_getDeviceId = 376u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputEvent_getSource = 377u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputEvent_getType = 378u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputEvent_release = 379u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputEvent_toJava = 380u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_attachLooper = 381u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_detachLooper = 382u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_finishEvent = 383u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_fromJava = 384u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_getEvent = 385u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_hasEvents = 386u;
inline constexpr std::uint32_t ZB_INPUT_HC_AInputQueue_preDispatchEvent = 387u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_fromJava = 388u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getAction = 389u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getDownTime = 390u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getEventTime = 391u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getFlags = 392u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getKeyCode = 393u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getMetaState = 394u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getRepeatCount = 395u;
inline constexpr std::uint32_t ZB_INPUT_HC_AKeyEvent_getScanCode = 396u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_fromJava = 397u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getAction = 398u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getActionButton = 399u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getAxisValue = 400u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getButtonState = 401u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getClassification = 402u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getDownTime = 403u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getEdgeFlags = 404u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getEventTime = 405u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getFlags = 406u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalAxisValue = 407u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalEventTime = 408u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalOrientation = 409u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalPressure = 410u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalRawX = 411u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalRawY = 412u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalSize = 413u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalToolMajor = 414u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalToolMinor = 415u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalTouchMajor = 416u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalTouchMinor = 417u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalX = 418u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistoricalY = 419u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getHistorySize = 420u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getMetaState = 421u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getOrientation = 422u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getPointerCount = 423u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getPointerId = 424u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getPressure = 425u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getRawX = 426u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getRawY = 427u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getSize = 428u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getToolMajor = 429u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getToolMinor = 430u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getToolType = 431u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getTouchMajor = 432u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getTouchMinor = 433u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getX = 434u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getXOffset = 435u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getXPrecision = 436u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getY = 437u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getYOffset = 438u;
inline constexpr std::uint32_t ZB_INPUT_HC_AMotionEvent_getYPrecision = 439u;

inline constexpr std::uint32_t ZB_INPUT_HC_FIRST = 376u;
inline constexpr std::uint32_t ZB_INPUT_HC_LAST = 439u;

}  // namespace zb
