#!/usr/bin/env python3
"""Generate the arm EABI syscall tables used by core/src/syscalls.cpp.

Reads unistd-eabi.h from the NDK sysroot and writes:
  core/src/gen/syscall_nrs_arm.h    inline constexpr NR_<name> constants
  core/src/gen/syscall_names_arm.inc  {number, "name"} rows
The outputs are committed, so building core/ does not need the NDK.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NDK = os.environ.get("NDK", os.path.expanduser("~/android-ndk-r29"))
NDK_HOST = os.environ.get("NDK_HOST", "linux-arm64")
HEADER = os.path.join(NDK, "toolchains", "llvm", "prebuilt", NDK_HOST, "sysroot", "usr", "include",
                      "arm-linux-androideabi", "asm", "unistd-eabi.h")

# arch/arm/include/uapi/asm/unistd.h: __ARM_NR_BASE = 0x0f0000
ARM_PRIVATE = [
    ("ARM_breakpoint", 0xF0001),
    ("ARM_cacheflush", 0xF0002),
    ("ARM_usr26", 0xF0003),
    ("ARM_usr32", 0xF0004),
    ("ARM_set_tls", 0xF0005),
    ("ARM_get_tls", 0xF0006),
]


def main():
    pattern = re.compile(r"^#define __NR_(\w+) \(__NR_SYSCALL_BASE \+ (\d+)\)")
    entries = []
    with open(HEADER) as f:
        for line in f:
            m = pattern.match(line)
            if m:
                entries.append((m.group(1), int(m.group(2))))
    if not entries:
        sys.exit("no syscalls parsed from " + HEADER)
    entries += ARM_PRIVATE

    out_dir = os.path.join(ROOT, "core", "src", "gen")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "syscall_nrs_arm.h"), "w") as f:
        f.write("// Generated by tools/gen_syscalls.py from the NDK arm EABI header. Do not edit.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace zb {\n\n")
        for name, nr in entries:
            f.write("inline constexpr std::uint32_t NR_%s = %d;\n" % (name, nr))
        f.write("\n}  // namespace zb\n")
    with open(os.path.join(out_dir, "syscall_names_arm.inc"), "w") as f:
        f.write("// Generated by tools/gen_syscalls.py from the NDK arm EABI header. Do not edit.\n")
        for name, nr in entries:
            f.write('{%d, "%s"},\n' % (nr, name))
    print("generated %d syscalls" % len(entries))


if __name__ == "__main__":
    main()
