#!/usr/bin/env python3
"""Generate the EGL host-call protocol and Task 1 dispatcher.

The Khronos registry copy was downloaded on 2026-09-17 from:
https://raw.githubusercontent.com/KhronosGroup/EGL-Registry/main/api/egl.xml

Inputs:
  third_party/registry/egl.xml                 pinned Khronos registry
  NDK sysroot/usr/include/EGL/egl.h            exported EGL core names
  core/src/gen/hostcalls.inc                   guest stub index assignment

Outputs are committed. Run with --check to reject stale files.
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

sys.dont_write_bytecode = True
import gen_stubs


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "third_party", "registry", "egl.xml")
HOSTCALLS = os.path.join(ROOT, "core", "src", "gen", "hostcalls.inc")
EXPECTED_EGL = 44
HEADER = "Generated by tools/gen_egl.py. Do not edit."

# Object handles crossing the guest boundary as 32-bit table indices (Task 3's
# HostEgl::handle<T>/set_handle). EGLNativeWindowType additionally resolves through
# HostNativeWindow's own table (Task 5).
HANDLE_TYPES = {"EGLDisplay", "EGLConfig", "EGLContext", "EGLSurface", "EGLNativeWindowType"}

# Other opaque types that cross as plain scalars (their host value, not translated).
POINTER_TYPES = HANDLE_TYPES | {
    "EGLClientBuffer",
    "EGLImage",
    "EGLSync",
    "EGLNativeDisplayType",
    "EGLNativePixmapType",
    "__eglMustCastToProperFunctionPointerType",
}

# Semantic handlers from the approved design (arrays, strings, proc addresses, thread-local
# getters and the config/window/surface handle chores that need more than a marshaled call).
HANDWRITTEN = {
    "eglChooseConfig",
    "eglCreateWindowSurface",
    "eglGetConfigAttrib",
    "eglGetConfigs",
    "eglGetCurrentContext",
    "eglGetCurrentDisplay",
    "eglGetCurrentSurface",
    "eglGetProcAddress",
    "eglQueryString",
    "eglQuerySurface",
    "eglQueryContext",
    "eglSwapBuffers",
}

# EGLint*/EGLAttrib* out-parameters that write exactly one element (eglInitialize's major and
# minor, eglGetSyncAttrib's value). Attribute-list arrays (name == "attrib_list") are always
# EGL_NONE-terminated with no declared length, and native_window/native_pixmap/native_display
# raw void* parameters have no declared length either: both stay outside MECHANICAL and fall
# through to a hand-written case in a later task, the same way unresolvable GL pointers do.
SINGLE_ELEMENT_OUT = {"major", "minor", "value"}


class Parameter:
    def __init__(self, declaration, name, ptype):
        self.declaration = declaration
        self.name = name
        self.ptype = ptype

    @property
    def pointer(self):
        return "*" in self.declaration

    @property
    def const(self):
        return "const" in self.declaration.split()


class Command:
    def __init__(self, name, result, result_ptype, parameters):
        self.name = name
        self.result = result
        self.result_ptype = result_ptype
        self.parameters = parameters


def element_text(element):
    return "".join(element.itertext()).strip()


def registry_commands():
    root = ET.parse(REGISTRY).getroot()
    definitions = {}
    for node in root.findall("./commands/command"):
        proto = node.find("proto")
        if proto is None:
            continue
        name = proto.findtext("name")
        definitions[name] = node

    commands = {}
    for name, node in definitions.items():
        proto = node.find("proto")
        result_ptype = proto.findtext("ptype")
        result = element_text(proto)[:-len(name)].strip()
        parameters = []
        for param in node.findall("param"):
            param_name = param.findtext("name")
            declaration = element_text(param)
            ptype = param.findtext("ptype")
            if not param_name or not re.search(r"\b%s\b" % re.escape(param_name), declaration):
                sys.exit("egl.xml: malformed parameter in " + name)
            parameters.append(Parameter(declaration, param_name, ptype))
        commands[name] = Command(name, result, result_ptype, parameters)
    return commands


def committed_hostcalls():
    rows = []
    row = re.compile(r'^\{(\d+), "([^"]+)", "([^"]+)"\},$')
    with open(HOSTCALLS) as source:
        for line in source:
            match = row.match(line.strip())
            if match:
                rows.append((int(match.group(1)), match.group(2), match.group(3)))
    return rows


def checked_surface():
    commands = registry_commands()
    header_names = gen_stubs.egl_names()
    if len(header_names) != EXPECTED_EGL:
        sys.exit("egl.h: expected %d functions, got %d" % (EXPECTED_EGL, len(header_names)))
    missing = sorted(set(header_names) - set(commands))
    if missing:
        sys.exit("egl.xml: command definition missing for " + ", ".join(missing))

    base = len(gen_stubs.gles2_names()) + len(gen_stubs.android_names())
    expected_rows = [(base + index, "libEGL.so", name) for index, name in enumerate(header_names)]
    core_names = set(header_names)
    actual_rows = [row for row in committed_hostcalls()
                   if row[1] == "libEGL.so" and row[2] in core_names]
    if actual_rows != expected_rows:
        sys.exit("core/src/gen/hostcalls.inc disagrees with tools/gen_stubs.py for libEGL.so")

    return [commands[name] for name in header_names], base


def length_rule(parameter):
    """None when unresolvable (falls through to a hand-written case); otherwise the element
    count for call.pointer<T>(position, count, permission)."""
    if parameter.ptype not in ("EGLint", "EGLAttrib"):
        return None
    if parameter.const:
        return None
    if parameter.name in SINGLE_ELEMENT_OUT:
        return 1
    return None


def mechanical(command):
    if command.name in HANDWRITTEN:
        return False
    for parameter in command.parameters:
        if parameter.ptype in HANDLE_TYPES:
            continue
        if not parameter.pointer:
            continue
        if length_rule(parameter) is None:
            return False
    return True


def backend_header(commands):
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <bit>",
        "#include <cstdint>",
        "#include <initializer_list>",
        "#include <type_traits>",
        "",
        "namespace zb {",
        "",
        "using EGLint = std::int32_t;",
        "using EGLenum = std::uint32_t;",
        "using EGLBoolean = std::uint32_t;",
        "using EGLAttrib = std::intptr_t;",
        "using EGLTime = std::uint64_t;",
        "using EGLDisplay = void*;",
        "using EGLConfig = void*;",
        "using EGLContext = void*;",
        "using EGLSurface = void*;",
        "using EGLClientBuffer = void*;",
        "using EGLImage = void*;",
        "using EGLSync = void*;",
        "using EGLNativeWindowType = void*;",
        "using EGLNativeDisplayType = void*;",
        "using EGLNativePixmapType = void*;",
        "using __eglMustCastToProperFunctionPointerType = void*;",
        "",
        "inline constexpr EGLint kEglSuccess = 0x3000;",
        "inline constexpr EGLint kEglBadDisplay = 0x3008;",
        "inline constexpr EGLint kEglBadContext = 0x3006;",
        "inline constexpr EGLint kEglBadSurface = 0x300d;",
        "inline constexpr EGLint kEglBadParameter = 0x3004;",
        "",
        "template <typename T>",
        "inline std::uint64_t egl_backend_word(T value) {",
        "    if constexpr (std::is_pointer_v<T>) {",
        "        return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(value));",
        "    } else if constexpr (std::is_signed_v<T>) {",
        "        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<T>>(value));",
        "    } else {",
        "        return static_cast<std::uint64_t>(value);",
        "    }",
        "}",
        "",
        "// The portable EGL seam. Android overrides the typed entry points; host tests use",
        "// invoke() to record the same typed calls without linking a real EGL driver.",
        "class EglBackend {",
        "public:",
        "    virtual ~EglBackend() = default;",
        "",
    ]
    for command in commands:
        params = ", ".join(parameter.declaration for parameter in command.parameters) or "void"
        args = ", ".join("egl_backend_word(%s)" % parameter.name for parameter in command.parameters)
        invocation = 'invoke("%s", {%s})' % (command.name, args)
        lines.append("    virtual %s %s(%s) {" % (command.result, command.name, params))
        if command.result == "void":
            lines.append("        (void)%s;" % invocation)
        elif command.result_ptype in POINTER_TYPES or command.result_ptype is None:
            lines.append("        return reinterpret_cast<%s>(static_cast<std::uintptr_t>(%s));" %
                         (command.result, invocation))
        else:
            lines.append("        return static_cast<%s>(%s);" % (command.result, invocation))
        lines.append("    }")
    lines += [
        "",
        "protected:",
        "    virtual std::uint64_t invoke(const char* name,",
        "                                 std::initializer_list<std::uint64_t> arguments) = 0;",
        "};",
        "",
        "}  // namespace zb",
    ]
    return "\n".join(lines) + "\n"


def hostcalls_header(commands, base):
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace zb {",
        "",
        "inline constexpr std::uint32_t kEglHostCallFirst = %du;" % base,
        "inline constexpr std::uint32_t kEglHostCallLast = %du;" % (base + len(commands) - 1),
        "inline constexpr std::size_t kEglHostCallCount = %du;" % len(commands),
        "",
    ]
    for index, command in enumerate(commands):
        lines.append("inline constexpr std::uint32_t ZB_EGL_HC_%s = %du;" %
                     (command.name, base + index))
    lines += [
        "",
        "struct EglHostCallInfo {",
        "    std::uint32_t index;",
        "    const char* name;",
        "};",
        "",
        "inline constexpr std::array<EglHostCallInfo, kEglHostCallCount> kEglHostCalls{{",
    ]
    for index, command in enumerate(commands):
        lines.append('    {%du, "%s"},' % (base + index, command.name))
    lines += ["}};", "", "}  // namespace zb"]
    return "\n".join(lines) + "\n"


def dispatch_include(commands):
    manual_names = [command.name for command in commands if not mechanical(command)]
    lines = [
        "// " + HEADER,
    ]
    for name in manual_names:
        lines.append("bool zbegl_manual_%s(HostEgl& host, HostEgl::Call& call);" % name)
    lines += [
        "",
        "bool HostEgl::dispatch(Call& call) {",
        "    switch (call.index()) {",
    ]
    for command in commands:
        lines.append("    case ZB_EGL_HC_%s: {" % command.name)
        if not mechanical(command):
            lines.append("        return zbegl_manual_%s(*this, call);" % command.name)
        else:
            for position, parameter in enumerate(command.parameters):
                if parameter.ptype in HANDLE_TYPES:
                    lines.append("        %s %s = call.handle<%s>(%d);" %
                                 (parameter.ptype, parameter.name, parameter.ptype, position))
                    lines.append("        if (!call.valid()) return true;")
                elif not parameter.pointer:
                    ptype = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                    lines.append("        const %s %s = call.scalar<%s>(%d);" %
                                 (ptype, parameter.name, ptype, position))
            for position, parameter in enumerate(command.parameters):
                if parameter.ptype in HANDLE_TYPES or not parameter.pointer:
                    continue
                declaration = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                pointee = parameter.ptype
                elements = length_rule(parameter)
                permission = "kPageRead" if parameter.const else "kPageRead | kPageWrite"
                lines.append("        %s %s = call.pointer<%s>(%d, %du, %s);" %
                             (declaration, parameter.name, pointee, position, elements, permission))
            lines.append("        if (!call.valid()) return true;")
            args = ", ".join(parameter.name for parameter in command.parameters)
            invocation = "backend_.%s(%s)" % (command.name, args)
            if command.result == "void":
                lines.append("        %s;" % invocation)
            elif command.result_ptype in HANDLE_TYPES:
                lines.append("        call.set_handle(%s);" % invocation)
            else:
                lines.append("        call.set_result(%s);" % invocation)
            lines.append("        return true;")
        lines.append("    }")
    lines += [
        "    default:",
        "        return false;",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def generate():
    commands, base = checked_surface()
    return {
        "core/include/zb/egl_backend.h": backend_header(commands),
        "core/include/zb/egl_hostcalls.h": hostcalls_header(commands, base),
        "core/src/gen/egl_dispatch.inc": dispatch_include(commands),
    }


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen_egl.py [--check]")
    stale = []
    for path, content in generate().items():
        full = os.path.join(ROOT, path)
        if check:
            try:
                with open(full) as source:
                    current = source.read()
            except OSError:
                current = None
            if current != content:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as output:
                output.write(content)
            print("wrote " + path)
    if stale:
        print("stale generated files (run tools/gen_egl.py): " + ", ".join(stale))
        sys.exit(1)
    if check:
        print("generated EGL files are up to date")


if __name__ == "__main__":
    main()
