#!/usr/bin/env python3
"""Generate the guest JNIEnv/JavaVM tables and the flat JNI host-call list.

Inputs:
  NDK jni.h                      the JNINativeInterface and JNIInvokeInterface slot order
  HOST_CALLS below               the flat host calls (index 0xFC00 + position)
  HOST_SLOTS below               JNINativeInterface slots served by a host stub
                                 (index 0xFB00 + slot number); every other slot is the
                                 guest C function zbjni_<Name> in guest/zbjni/zbjni.c

Outputs (committed, never edited by hand):
  core/include/zb/jni_hostcalls.h   ZB_JNI_HC_<Name> indices, shared by host and guest
  core/src/gen/jni_hostcalls.inc    {index, "Name"} rows for host diagnostics
  guest/zbjni/gen/hostcalls.S       ARM-mode svc stubs zbjni_hc_<Name> and zbjni_slot_<Name>
  guest/zbjni/gen/hostcalls.h       C prototypes of those stubs
  guest/zbjni/gen/tables.inc        designated initializers of both interface tables

Usage: gen_jni.py            write the outputs
       gen_jni.py --check    exit 1 if any committed output differs from a fresh generation
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NDK = os.environ.get("NDK", os.path.expanduser("~/android-ndk-r29"))
NDK_HOST = os.environ.get("NDK_HOST", "linux-arm64")
JNI_H = os.path.join(NDK, "toolchains", "llvm", "prebuilt", NDK_HOST, "sysroot", "usr", "include", "jni.h")

HOST_CALL_BASE = 0x5A0000
HOST_CALL_FIRST = 0xFC00  # ZB_JNI_HOST_CALL_FIRST in core/include/zb/jni_protocol.h
HOST_CALL_LAST = 0xFCFF
SLOT_STUB_FIRST = 0xFB00  # ZB_JNI_SLOT_STUB_FIRST
NATIVE_INTERFACE_FUNCTIONS = 229
INVOKE_INTERFACE_FUNCTIONS = 5

# Slots served by a host stub instead of guest C (performance fallback). A host stub needs a
# host implementation in core/src/jni/host_jni.cpp; none exists yet, so the set is empty.
HOST_SLOTS = set()

W = "uint32_t"
# (name, return type, parameters). Every parameter is one guest word.
HOST_CALLS = [
    ("Register", W, ["api"]),
    ("FindClass", W, ["name"]),
    ("GetSuperclass", W, ["cls"]),
    ("IsAssignableFrom", W, ["from", "to"]),
    ("GetMethodID", W, ["cls", "name", "signature", "is_static", "shorty_out"]),
    ("GetFieldID", W, ["cls", "name", "signature", "is_static"]),
    ("GetMethodShorty", W, ["method", "shorty_out"]),
    ("FromReflectedMethod", W, ["method", "shorty_out"]),
    ("FromReflectedField", W, ["field"]),
    ("ToReflectedMethod", W, ["cls", "method", "is_static"]),
    ("ToReflectedField", W, ["cls", "field", "is_static"]),
    ("AllocObject", W, ["cls"]),
    ("GetObjectClass", W, ["obj"]),
    ("IsInstanceOf", W, ["obj", "cls"]),
    ("IsSameObject", W, ["a", "b"]),
    ("GetObjectRefType", W, ["obj"]),
    ("CallMethodA", "uint64_t", ["kind", "type", "obj", "cls", "method", "args"]),
    ("GetField", "uint64_t", ["is_static", "type", "obj", "field"]),
    ("SetField", "void", ["is_static", "type", "obj", "field", "low", "high"]),
    ("NewString", W, ["chars", "length"]),
    ("NewStringUTF", W, ["utf"]),
    ("GetStringLength", W, ["str"]),
    ("GetStringUTFLength", W, ["str"]),
    ("GetStringRegion", "void", ["str", "start", "length", "out"]),
    ("GetStringUTFRegion", "void", ["str", "start", "length", "out"]),
    ("GetArrayLength", W, ["array"]),
    ("GetArrayElementType", W, ["array"]),
    ("NewObjectArray", W, ["length", "cls", "initial"]),
    ("GetObjectArrayElement", W, ["array", "index"]),
    ("SetObjectArrayElement", "void", ["array", "index", "value"]),
    ("NewPrimitiveArray", W, ["type", "length"]),
    ("GetPrimitiveArrayRegion", "void", ["type", "array", "start", "length", "out"]),
    ("SetPrimitiveArrayRegion", "void", ["type", "array", "start", "length", "in"]),
    ("NewGlobalRef", W, ["obj"]),
    ("DeleteGlobalRef", "void", ["ref"]),
    ("NewWeakGlobalRef", W, ["obj"]),
    ("DeleteWeakGlobalRef", "void", ["ref"]),
    ("NewLocalRef", W, ["obj"]),
    ("DeleteLocalRef", "void", ["ref"]),
    ("EnsureLocalCapacity", W, ["capacity"]),
    ("PushLocalFrame", W, ["capacity"]),
    ("PopLocalFrame", W, ["result"]),
    ("Throw", W, ["throwable"]),
    ("ThrowNew", W, ["cls", "message"]),
    ("ExceptionOccurred", W, []),
    ("ExceptionDescribe", "void", []),
    ("ExceptionClear", "void", []),
    ("ExceptionCheck", W, []),
    ("FatalError", "void", ["message"]),
    ("MonitorEnter", W, ["obj"]),
    ("MonitorExit", W, ["obj"]),
    ("RegisterNatives", W, ["cls", "methods", "count"]),
    ("UnregisterNatives", W, ["cls"]),
    ("NewDirectByteBuffer", W, ["address", "capacity_low", "capacity_high"]),
    ("GetDirectBufferAddress", W, ["buffer"]),
    ("GetDirectBufferCapacity", "uint64_t", ["buffer"]),
    ("GetEnv", W, []),
    ("AttachCurrentThread", W, ["env_out", "args", "daemon"]),
    ("DetachCurrentThread", W, []),
]

HEADER = "Generated by tools/gen_jni.py. Do not edit."


def interface_functions(text, struct):
    body = re.search(r"struct %s \{(.*?)\n\};" % struct, text, re.S)
    if body is None:
        sys.exit("jni.h: struct %s not found" % struct)
    slots = []
    for member in body.group(1).split(";"):
        member = member.strip()
        if not member:
            continue
        m = re.search(r"\(\s*\*\s*(\w+)\s*\)", member)
        if m:
            slots.append((m.group(1), False))
        elif re.fullmatch(r"void\*\s+reserved\d", member):
            slots.append((member.split()[-1], True))
        else:
            sys.exit("jni.h: unexpected member in %s: %s" % (struct, member))
    return slots


def generate(host_slots):
    text = re.sub(r"/\*.*?\*/", "", open(JNI_H).read(), flags=re.S)
    native = interface_functions(text, "JNINativeInterface")
    invoke = interface_functions(text, "JNIInvokeInterface")
    if sum(1 for _, reserved in native if not reserved) != NATIVE_INTERFACE_FUNCTIONS:
        sys.exit("jni.h: expected %d JNINativeInterface functions" % NATIVE_INTERFACE_FUNCTIONS)
    if sum(1 for _, reserved in invoke if not reserved) != INVOKE_INTERFACE_FUNCTIONS:
        sys.exit("jni.h: expected %d JNIInvokeInterface functions" % INVOKE_INTERFACE_FUNCTIONS)
    unknown = host_slots - set(name for name, reserved in native if not reserved)
    if unknown:
        sys.exit("HOST_SLOTS names unknown slots: %s" % ", ".join(sorted(unknown)))
    if HOST_CALL_FIRST + len(HOST_CALLS) - 1 > HOST_CALL_LAST:
        sys.exit("too many JNI host calls for 0x%x-0x%x" % (HOST_CALL_FIRST, HOST_CALL_LAST))

    outputs = {}

    lines = ["/* %s */" % HEADER, "#pragma once", ""]
    for i, (name, _, _) in enumerate(HOST_CALLS):
        lines.append("#define ZB_JNI_HC_%s 0x%xu" % (name, HOST_CALL_FIRST + i))
    lines.append("#define ZB_JNI_HC_COUNT %du" % len(HOST_CALLS))
    outputs["core/include/zb/jni_hostcalls.h"] = "\n".join(lines) + "\n"

    lines = ["// %s" % HEADER]
    for i, (name, _, _) in enumerate(HOST_CALLS):
        lines.append('{0x%xu, "%s"},' % (HOST_CALL_FIRST + i, name))
    outputs["core/src/gen/jni_hostcalls.inc"] = "\n".join(lines) + "\n"

    asm = ["@ %s" % HEADER, ".syntax unified", ".arm", ".text", ""]
    stubs = [("zbjni_hc_" + name, HOST_CALL_FIRST + i) for i, (name, _, _) in enumerate(HOST_CALLS)]
    stubs += [("zbjni_slot_" + name, SLOT_STUB_FIRST + slot) for slot, (name, _) in enumerate(native)
              if name in host_slots]
    for symbol, index in stubs:
        asm += [
            ".global %s" % symbol,
            ".hidden %s" % symbol,
            ".type %s, %%function" % symbol,
            ".p2align 2",
            "%s:" % symbol,
            "    svc #0x%x" % (HOST_CALL_BASE | index),
            "    bx lr",
            ".size %s, . - %s" % (symbol, symbol),
            "",
        ]
    outputs["guest/zbjni/gen/hostcalls.S"] = "\n".join(asm)

    lines = ["/* %s */" % HEADER, "#pragma once", "", "#include <stdint.h>", ""]
    for name, result, params in HOST_CALLS:
        args = ", ".join("uint32_t " + p for p in params) or "void"
        lines.append("%s zbjni_hc_%s(%s);" % (result, name, args))
    for name in sorted(host_slots):
        lines.append("void zbjni_slot_%s(void);" % name)
    outputs["guest/zbjni/gen/hostcalls.h"] = "\n".join(lines) + "\n"

    lines = ["/* %s */" % HEADER, "", "static const struct JNINativeInterface zbjni_native_interface = {"]
    for slot, (name, reserved) in enumerate(native):
        if reserved:
            lines.append("    .%s = NULL," % name)
        elif name in host_slots:
            lines.append("    .%s = (__typeof__(((struct JNINativeInterface*)0)->%s))zbjni_slot_%s, /* host stub 0x%x */"
                         % (name, name, name, SLOT_STUB_FIRST + slot))
        else:
            lines.append("    .%s = zbjni_%s," % (name, name))
    lines += ["};", "", "static const struct JNIInvokeInterface zbjni_invoke_interface = {"]
    for name, reserved in invoke:
        lines.append("    .%s = %s," % (name, "NULL" if reserved else "zbjni_" + name))
    lines.append("};")
    outputs["guest/zbjni/gen/tables.inc"] = "\n".join(lines) + "\n"
    return outputs


def self_test():
    # The host-stub path is unused while HOST_SLOTS is empty; generate one to keep it working.
    outputs = generate({"ExceptionCheck"})
    slot = 228  # ExceptionCheck: slot number in JNINativeInterface, reserved entries included
    expect = [
        ("guest/zbjni/gen/tables.inc", "zbjni_slot_ExceptionCheck, /* host stub 0x%x */" % (SLOT_STUB_FIRST + slot)),
        ("guest/zbjni/gen/hostcalls.S", "svc #0x%x" % (HOST_CALL_BASE | SLOT_STUB_FIRST | slot)),
        ("guest/zbjni/gen/hostcalls.h", "void zbjni_slot_ExceptionCheck(void);"),
    ]
    for path, needle in expect:
        if needle not in outputs[path]:
            sys.exit("self-test: %s lacks %r" % (path, needle))


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen_jni.py [--check]")
    if check:
        self_test()
    stale = []
    for path, content in generate(HOST_SLOTS).items():
        full = os.path.join(ROOT, path)
        if check:
            try:
                current = open(full).read()
            except OSError:
                current = None
            if current != content:
                stale.append(path)
            continue
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w") as f:
            f.write(content)
        print("wrote %s" % path)
    if stale:
        print("stale generated files (run tools/gen_jni.py): %s" % ", ".join(stale))
        sys.exit(1)
    if check:
        print("generated JNI files are up to date")


if __name__ == "__main__":
    main()
